sudo: false

env:
  global:
    - secure: "jmOtD3hF+GhcvkenMOi7sqqSD2DVUD1f+2qtCC8DDEXeHOt2WoFqTVbkzZ7f/chtcRTtk2j6wtU3Fj90947koq+dgn4q0qeaGiU3JMshxKb5MkQqxG9dxqedzP0tCIj5uYGvgQQ3scOOApAokfVjrJxx52hUgDN5DssfUHnIiajaTfQ8UZpfmSbpxRLDy6NYsWDZIZSuR1ORNAvvdIibyOoyJN+79fTezXR9iOn7TwCH9dI2PBP/UrQAgILvCXG29rToTBzSYUHFs6uGw2uIpoTh/SXVP0Bl4YNRJWAzvuvO/mKiM+AWJOSB07h05a0hZre0IzavBDLsZwCQn+QXQsP0pgWm8e1Xn/7m4EtkbXSl3f/qRt5RZZ1nOYDXvtppFgX+qE/vOqnMvojrH7eZC8cUSP97PVFVncYoQMKbaDHs6OCsHMi/1ODKNBSj9RNJyY6ov/doCsSCuIuotR5B7yoTptHsUVZ3qb2LbaNYu3m+YNr8QVnpAzDP8TmF/6PjggYG6qgGcjmVZGcXBJLqNuk1qS1cGAgt3h+x/4trdnxFeAFdUcIajfeeFfnyGIc785myRNTj9RmBpqTAZEeuK2bgU5IWAovh5uIyZEvARO2561J1U4UQmhbah24MLDyumaHRDEqd8qBW4VX217g4DSgjon1aEBzEPCGXZHyw/7E="
    - secure: "CMR09ljbKa86pjeBAbFQqB5YkKepfArI6OM4hZ9Nhz1mT5cfd7VSm24NPtDIeXWHT0YiGjR6py6Bk5l3FTfZ9s+ntzHqqxdwEsewTe3HodRafYfa2hJYHs5YD2+5WaAsmkToiz98j1Mce3frYBaa2pcSQk4cuMrA4nClcNlbH9ExV/tGukfqyKXWu+Szjydy+JKGZ4Yqs5hgOC+tSrXPve2joXlJWrQ1G85v2U9IKZViyGpReqSpH/bZSc+hgeD4VMa7uGc52kU3wR6A1y04IyE7tG4l3fopBNH1Pk1NA3/9Rx00nvEcvmb8pUfHkmzLfcjmWDkgbpkn9R5F5YsYDRADWrzaNBM2PJi+KVmqUwtm+s3pVxUK3pZ0NQvbO6z1jmN+dgD6kk1YV/GIKQ5deUymNkpcXZLlAlpxi/IlEQc9dIu02xNGLVbt60ykRyWO55HU4Kf2O8cSO1P8fMzqaI47bQreFRQfX0Xgtdm6tBKNX9c7LKlBhP5Vv6ki//5bVGbvsY3pbYrhXYrkhuok3sQu/4pWZoEaeEKKrWPCsrmNn+W4Shn6YT5wlgfjAy2sJ4X11GoZe5sNUWXuheMxmG1hUPLU59KaxKt6/nQR0fS9h5jnoMupske6HIsSx3fIssFQXCysoOONFIZ9nuWJSshBw7DSvT6j6M2J7G4qI7M="

language: scala

jdk:
- oraclejdk7
- oraclejdk8

scala:
- 2.10.5
- 2.11.5

cache:
  directories:
  - $HOME/.ivy2
  - $HOME/.sbt

script:
- ./buildall.sh

notifications:
  email:
    recipients:
    - lossyrob@gmail.com

before_deploy:
- export SCALIPER_VERSION_SUFFIX="-${TRAVIS_COMMIT:0:7}"

deploy:
- provider: script
  script: .travis/deploy.sh
  skip_cleanup: true
  on:
    repo: azavea/scaliper
    branch: master
    jdk: oraclejdk7
    scala: 2.10.5

after_deploy:
- rm -f "${HOME}/.bintray/.credentials"
