sudo: false

env:
  global:
    - secure: "Gz2e787fD4N37W24zoGSQF/SXCZcI1boPz2wTMegDe8Jytcux7om1mO864wy/MlwtlS3BLrg26ac4af2HSvC539hmIuu4u1iIq4ZNCXtu8Io/P5tBWnRhUCJltPM1NwXtGKhyo0ZfV996/KuCkj3kkzBmDVijq1exQegMgwtUlwNquupB9Rrrjr/u5wKMwNGdPiCpU4ukOZCPoAiFuBTyNP4a2hXsB+pAPJ19EJojqpqrJtjZkWhF+4w7SBGaV1PRs0Qb2xdAMQOU8ovQKRhgPg7GaaXTs9ef6xR/n7rNjlFw1neNmb/VZ5uo4HQZ9C8fMb0a62MJMDa6bsXAS0BU4EeJaZvSjlzZVJmK4REAIJv87w9pF0V//YhrPmrCTlYksiAaP7HrS6yB0iKERsHrBNdlWSOk9xLxdDBuMmGKOeQPGijrmLyMmSQdz6rhbhOU5uZjf8241WVHvmzcTB9hV2AYY49Nvzj46RQdVWEs+dyPkI2vEZRU+Zdvaq3m6J57HLvJbUYoKuKelYpNEHZbbX7pVQHacKEVGa9kh5PeAdz1cij5wJ5bTORDSvcLmWyBm/BHVfk9kE1OuAEL4bygEzHg9YsnG7Rca+qAo6ii4IVn/CjvDUDcUgwlqd4NhFMfxGA7Zt4j6vDDGHHnvHfAAOF0oRv3FB9zUWZbHGwrO4="
    - secure: "KuDJ9kc6TjlvOb7qF1mJ4K7TWbJMhxSSVzX6X2UfIbERBISkE/xoVAH+l6xOP/9UwitYFvGp+O4n9IOAqFSzgRYy7P0d8JXxQfYmXWX8kZMUtkgsR51jZNvpMM5aCE0Mhw2MR+/YhCHXEMIWGGO+qXohGN2rIW9ok8vj4CuFnOaZJJXw+RKSlrHjLk/RjKjEOYbFbxUyltKTJw8lNs8Obc/5gc9TSvsAZ9WC8pETSFxcGTVnAzgUzcMH86EnnGItPagWPzCQPc73dNNNcuRESymI9AM0v9XULjC0LjolzGGeomvxqph0XVx80whR+iSpAwINB5/m3rAN3JvACGqg38LvfSpnU2dM3MpzDlShZ7U4i+y+ZhOUnWuxjanxjKrxBE+D84m4t0NRinz3fBdw1yvSKNgTZotG7eAbJVnk6frA8lfC3rsGn5VdfkV27EmHd58yNwCSA9ywHJIdMHbzOTQgA2DLqYN51hBn3XX3+1goZOYnIyqfPf4mbqqZs++VkjFGCUtTeEnJofokaR0cc7jr7d6+S5Y5knvFfBGPt524G8u07XHKnRRDml5SmQcrtecHRc9n3HBVzQll67QuHkt5v1wFdpP8Tnxl2zfI6KOmHf9jbcc9kUYuJiPMAeTeRoT7SVxFhQ7plf834wWa4CSYOTDv1LCl1zH+ffhQo5Q="

language: scala

jdk:
- oraclejdk7
- oraclejdk8

scala:
- 2.10.5
- 2.11.5

cache:
  directories:
  - $HOME/.ivy2
  - $HOME/.sbt

script:
- ./buildall.sh

notifications:
  email:
    recipients:
    - lossyrob@gmail.com

before_deploy:
- export SCALIPER_VERSION_SUFFIX="-${TRAVIS_COMMIT:0:7}"

deploy:
- provider: script
  script: .travis/deploy.sh
  skip_cleanup: true
  on:
    repo: azavea/scaliper
    branch: master
    jdk: oraclejdk7
    scala: 2.10.5

after_deploy:
- rm -f "${HOME}/.bintray/.credentials"
