sudo: false

env:
  global:
    - secure: "zzAHoNzLBnDyXZL8O6bkJWXD5MyC13tPOmre3WzkXJssDqvVGWRXoxctOmi/gxAP4Cf/qjMiNhgrqUrYs+s9fJ57tB3OCjzKt8U0xSucNY3aPrhDBpNSRtpLtxePKFc0DGlXnTWNtM/GUSYr+SRg4cdt+hj9TKUDNgaK5ljMQuDihZYWa8J6GuE54lM7MDz6KH1FbmknRAkDKdiHf5yUwXRGdPe9w7BkpDMPx4k8T5bb2uqtcom1wToezBSqua/nkEsS8qftrOkJDzb+nDHE25T6mJBJxRQMmd4tJj2uWHJfWMDt6LitQ9zMXdagqTthl95/dZBvHasKSU3POb8IepL3866+FQ6DKqwJZaRu8zV2ciB971+EXt1nmOQpLuaYjgdI3bAX1h+V8iCJSem3+Y2NqRQjK5eWXsZqbC/2dBr6Tz8nvaUBF5XVwrECBJfujHgXGrNUePN8Bd+eEo3dCSBjmR9GXMSl5QtEFhPvcL/8e1QcvMtR+oPabi5VwYcBuN+REEGGYRIQ2hCsj8VeZ2cWwtbOOd2wITKSNY1CR2NVGQGwhJKE/RQMgrK6YkpQIbchCe/2QmSPWqoxRnjndDMpNUeZLYM/qUA8/LBm0zFjBZZmZ1sUc+fhbFYE1xE5m/uHBZ8CyBznR+f7CmiTZPYp8fKzean92mJ70yVq1qI="

    - secure: "qjV7c7eVPPhSLzpY8p7ECFzVsccqZrdb63I+11Sh/A2vxs5TX/SyZmG2j5OgHl6yUqhLd7ZeOKQBQOU8GnaapPFIc+2l6aJARVgutC9qVszyuqaqifwlbiSyoAkCCtW4TIo09LHJaA+uzj0LC5pUXK30SbvJi3sn8+gHJkKeGzFtZvo3bs75iroKFBBvFIGxh/cLEHz0H/aDnhPc+UWlY/0tzlmWpjL+ytNhmYGSKheo0AUJfUG9sYNH2j8KnLzfMSKvDJXEVCjeCtTx9lIsrnJL5hAyb8OPatxlpOZ83by2AZfG3PenHapGosVI5XFZvrmHD7czyV+ibZC+zAuuzI0EIv96DoAPMHMnlMQmqY8vaGQxirCNoUK8cSy0o0CwXBwQIsZ/M4kuB0JrvpaN40TPxcRp10yymvKwY6zuiTE4HeE84mhQ4stwWYXM51HqbP9olCglvgCwK5wo3D+6iDmjrqosWh18JldHSuVpF08bdfMmyTn4J2iDGU2TUFJViHAjCNsDGOfFTk09VmcPSyh0dqYic7CyyzxYxJCGsU5dwhCqDP6TsrvEX4zcB4DPOxHc6o/8j/VqThECgqDfYqMFqAhuWK6pmaT2miOvLkZY67+JNpv9vbPBo401i9BVRPBUIxnl2RN5gxOqSfQlozO0CFspX7/otLlKGMGb4DM="

language: scala

jdk:
- oraclejdk7
- oraclejdk8

scala:
- 2.10.5
- 2.11.5

cache:
  directories:
  - $HOME/.ivy2
  - $HOME/.sbt

script:
- ./buildall.sh

notifications:
  email:
    recipients:
    - lossyrob@gmail.com

before_deploy:
- export SCALIPER_VERSION_SUFFIX="-${TRAVIS_COMMIT:0:7}"

deploy:
- provider: script
  script: .travis/deploy.sh
  skip_cleanup: true
  on:
    repo: azavea/scaliper
    branch: master
    jdk: oraclejdk7
    scala: 2.10.5

after_deploy:
- rm -f "${HOME}/.bintray/.credentials"
